//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpLearning.Examples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpLearning.Examples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id;Pixel0_Channel0;Pixel1_Channel0;Pixel2_Channel0;Pixel3_Channel0;Pixel4_Channel0;Pixel5_Channel0;Pixel6_Channel0;Pixel7_Channel0;Pixel8_Channel0;Pixel9_Channel0;Pixel10_Channel0;Pixel11_Channel0;Pixel12_Channel0;Pixel13_Channel0;Pixel14_Channel0;Pixel15_Channel0;Pixel16_Channel0;Pixel17_Channel0;Pixel18_Channel0;Pixel19_Channel0;Pixel20_Channel0;Pixel21_Channel0;Pixel22_Channel0;Pixel23_Channel0;Pixel24_Channel0;Pixel25_Channel0;Pixel26_Channel0;Pixel27_Channel0;Pixel28_Channel0;Pixel29_Channel0;Pixel30_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cifar10_test_small {
            get {
                return ResourceManager.GetString("cifar10_test_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id;Pixel0_Channel0;Pixel1_Channel0;Pixel2_Channel0;Pixel3_Channel0;Pixel4_Channel0;Pixel5_Channel0;Pixel6_Channel0;Pixel7_Channel0;Pixel8_Channel0;Pixel9_Channel0;Pixel10_Channel0;Pixel11_Channel0;Pixel12_Channel0;Pixel13_Channel0;Pixel14_Channel0;Pixel15_Channel0;Pixel16_Channel0;Pixel17_Channel0;Pixel18_Channel0;Pixel19_Channel0;Pixel20_Channel0;Pixel21_Channel0;Pixel22_Channel0;Pixel23_Channel0;Pixel24_Channel0;Pixel25_Channel0;Pixel26_Channel0;Pixel27_Channel0;Pixel28_Channel0;Pixel29_Channel0;Pixel30_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cifar10_train_small {
            get {
                return ResourceManager.GetString("cifar10_train_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class;Pixel1;Pixel2;Pixel3;Pixel4;Pixel5;Pixel6;Pixel7;Pixel8;Pixel9;Pixel10;Pixel11;Pixel12;Pixel13;Pixel14;Pixel15;Pixel16;Pixel17;Pixel18;Pixel19;Pixel20;Pixel21;Pixel22;Pixel23;Pixel24;Pixel25;Pixel26;Pixel27;Pixel28;Pixel29;Pixel30;Pixel31;Pixel32;Pixel33;Pixel34;Pixel35;Pixel36;Pixel37;Pixel38;Pixel39;Pixel40;Pixel41;Pixel42;Pixel43;Pixel44;Pixel45;Pixel46;Pixel47;Pixel48;Pixel49;Pixel50;Pixel51;Pixel52;Pixel53;Pixel54;Pixel55;Pixel56;Pixel57;Pixel58;Pixel59;Pixel60;Pixel61;Pixel62;Pixel63;Pixel64;Pix [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mnist_small_test {
            get {
                return ResourceManager.GetString("mnist_small_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class;Pixel1;Pixel2;Pixel3;Pixel4;Pixel5;Pixel6;Pixel7;Pixel8;Pixel9;Pixel10;Pixel11;Pixel12;Pixel13;Pixel14;Pixel15;Pixel16;Pixel17;Pixel18;Pixel19;Pixel20;Pixel21;Pixel22;Pixel23;Pixel24;Pixel25;Pixel26;Pixel27;Pixel28;Pixel29;Pixel30;Pixel31;Pixel32;Pixel33;Pixel34;Pixel35;Pixel36;Pixel37;Pixel38;Pixel39;Pixel40;Pixel41;Pixel42;Pixel43;Pixel44;Pixel45;Pixel46;Pixel47;Pixel48;Pixel49;Pixel50;Pixel51;Pixel52;Pixel53;Pixel54;Pixel55;Pixel56;Pixel57;Pixel58;Pixel59;Pixel60;Pixel61;Pixel62;Pixel63;Pixel64;Pix [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mnist_small_train {
            get {
                return ResourceManager.GetString("mnist_small_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;fixed acidity&quot;;&quot;volatile acidity&quot;;&quot;citric acid&quot;;&quot;residual sugar&quot;;&quot;chlorides&quot;;&quot;free sulfur dioxide&quot;;&quot;total sulfur dioxide&quot;;&quot;density&quot;;&quot;pH&quot;;&quot;sulphates&quot;;&quot;alcohol&quot;;&quot;quality&quot;
        ///7;0.27;0.36;20.7;0.045;45;170;1.001;3;0.45;8.8;6
        ///6.3;0.3;0.34;1.6;0.049;14;132;0.994;3.3;0.49;9.5;6
        ///8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;10.1;6
        ///7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4;9.9;6
        ///7.2;0.23;0.32;8.5;0.058;47;186;0.9956;3.19;0.4;9.9;6
        ///8.1;0.28;0.4;6.9;0.05;30;97;0.9951;3.26;0.44;10.1;6
        ///6.2;0.32;0.16;7;0.045;30;136;0.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winequality_white {
            get {
                return ResourceManager.GetString("winequality_white", resourceCulture);
            }
        }
    }
}
